### ISSUE TITLE
Trees connected to each other issue.

### ISSUE THREAD

**Issue by Getblock** [Dudenn/TreeGravity#3]
multiple trees connected to each other in one hit sometimes doesnt replant and doesnt drop any wood

**Comment by Dudenn** [comment]
Multiple trees connected to one another, while houseProtection is OFF, will be treated as 1 tree. Therefore, 1 stack of logs will be dropped and ONLY the tree with the "lowest" base (whose lowest logs have the lowest Y value out of all logs) will be replanted. This mechanic was necessary in order to avoid saplings getting planted on top of each other and effectively having the tree logs getting replaced with saplings; kinda resulting in a "sapling tree". If you don't understand what I'm saying, message me on Spigot and I'll show you an example. 

Considering the autoreplant funtion can already give players 4+ free saplings that are effectively spawned into the game, not including saplings getting dropped or saplings dropping when leaves disappear, autoreplant bugging out on large, unnatural, and rare trees is a nonissue. Thank you for the feedback, I will address this mechanic again if it becomes a bigger issue.
